import AuthProvider from '@/components/providers/AuthProvider'
import type { Metadata } from 'next'
import { Frank_Ruhl_Libre } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'

const FrankRuhlLibre = Frank_Ruhl_Libre({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-FrankRuhlLibre',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${FrankRuhlLibre.variable}`}>
        <AuthProvider>
          <Toaster
            richColors
            toastOptions={{ classNames: { title: 'text-lg' } }}
          />
          <div className="font-FrankRuhlLibre">{children}</div>
        </AuthProvider>
      </body>
    </html>
  )
}
